"""Simplify donation system

Revision ID: 63d59f8c7814
Revises: 855d34d66675
Create Date: 2026-08-20 02:22:14.728741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d59f8c7814'
down_revision = '855d34d66675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_donations_checkout_request_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_donations_mpesa_receipt_number'), type_='unique')
        batch_op.drop_column('transaction_date')
        batch_op.drop_column('result_description')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('result_code')
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('mpesa_receipt_number')
        batch_op.drop_column('checkout_request_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('mpesa_receipt_number', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('result_code', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('result_description', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('transaction_date', sa.VARCHAR(length=30), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_donations_mpesa_receipt_number'), ['mpesa_receipt_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_donations_checkout_request_id'), ['checkout_request_id'])

    # ### end Alembic commands ###
