"""Add WhatsApp link to site settings

Revision ID: 8e9a056fb428
Revises: 63d59f8c7814
Create Date: 2026-08-24 00:13:24.337312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9a056fb428'
down_revision = '63d59f8c7814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('full_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)

    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mpesa_paybill', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('mpesa_account', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('meta_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('meta_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('copyright', sa.String(length=255), nullable=True))
        batch_op.alter_column('whatsapp',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.alter_column('whatsapp',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('copyright')
        batch_op.drop_column('meta_description')
        batch_op.drop_column('meta_title')
        batch_op.drop_column('mpesa_account')
        batch_op.drop_column('mpesa_paybill')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('full_name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###
