"""Prepare driver registration numbers

Revision ID: f42e6bf1f782
Revises: restore_payment_method
Create Date: 2026-08-24 12:21:56.416441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42e6bf1f782'
down_revision = 'restore_payment_method'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_members_member_id'), ['member_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_member_id'))
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
